### ISSUE TITLE
update.sh has wrong line 29?

### ISSUE THREAD

**Issue by washran** [rollingrhinoremix/rhino-update#19]
if [ ! -f "$HOME/.rhino/config/snapdpurge"]; then 
Shouldn't space be snapdpurge" ]; ?

**Comment by ajstrongdev** [comment]
I apologize but I am unable to understand what the issue is with the script by your description, would it be alright if you went more indepth with the issue?

**Comment by raluvy95** [comment]
Fixed in #20

**Comment by ajstrongdev** [comment]
Closed
