### ISSUE TITLE
zfs module not available for latest kernel 5.17.3-051703-generic

### ISSUE THREAD

**Issue by PerfMonk** [rollingrhinoremix/rhino-update#24]
laptop will not boot and drop to a busybox shell saying zfs module not loaded.

zfs works correctly with previous kernel 5.15.0-25-generic.

My root filesystem is on zfs encrypted.

bt@rhinos:~$ inxi -Faz
System:
  Kernel: 5.15.0-25-generic x86_64 bits: 64 compiler: gcc v: 11.2.0
    parameters: BOOT_IMAGE=/BOOT/ubuntu_ji6uoe@/vmlinuz-5.15.0-25-generic
    root=ZFS=rpool/ROOT/ubuntu_ji6uoe ro quiet splash
  Desktop: GNOME 42.0 tk: GTK 3.24.33 wm: gnome-shell dm: GDM3 42.0
    Distro: Ubuntu 22.04 (Jammy Jellyfish)
Machine:
  Type: Laptop System: ASUSTeK product: VivoBook_ASUSLaptop X513UA_M513UA
    v: 1.0 serial: <superuser required>
  Mobo: ASUSTeK model: X513UA v: 1.0 serial: <superuser required>
    UEFI: American Megatrends LLC. v: X513UA.305 date: 03/12/2021
Battery:
  ID-1: BAT0 charge: 38.7 Wh (100.0%) condition: 38.7/42.1 Wh (92.1%)
    volts: 11.8 min: 11.8 model: ASUSTeK ASUS Battery type: Li-ion serial: N/A
    status: Not charging cycles: 20
  Device-1: hidpp_battery_0 model: Logitech Wireless Mouse M325
    serial: <filter> charge: 100% (should be ignored) rechargeable: yes
    status: Discharging
CPU:
  Info: model: AMD Ryzen 7 5700U with Radeon Graphics bits: 64 type: MT MCP
    arch: Zen 2 family: 0x17 (23) model-id: 0x68 (104) stepping: 1
    microcode: 0x8608103
  Topology: cpus: 1x cores: 8 tpc: 2 threads: 16 smt: enabled cache:
    L1: 512 KiB desc: d-8x32 KiB; i-8x32 KiB L2: 4 MiB desc: 8x512 KiB
    L3: 8 MiB desc: 2x4 MiB
  Speed (MHz): avg: 1412 high: 1649 min/max: 1400/4370 boost: enabled
    scaling: driver: acpi-cpufreq governor: schedutil cores: 1: 1649 2: 1396
    3: 1397 4: 1397 5: 1397 6: 1397 7: 1397 8: 1395 9: 1401 10: 1397 11: 1397
    12: 1397 13: 1397 14: 1397 15: 1396 16: 1396 bogomips: 57488
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
  Vulnerabilities:
  Type: itlb_multihit status: Not affected
  Type: l1tf status: Not affected
  Type: mds status: Not affected
  Type: meltdown status: Not affected
  Type: spec_store_bypass
    mitigation: Speculative Store Bypass disabled via prctl and seccomp
  Type: spectre_v1
    mitigation: usercopy/swapgs barriers and __user pointer sanitization
  Type: spectre_v2 mitigation: Retpolines, IBPB: conditional, IBRS_FW,
    STIBP: conditional, RSB filling
  Type: srbds status: Not affected
  Type: tsx_async_abort status: Not affected
Graphics:
  Device-1: AMD Lucienne vendor: ASUSTeK driver: amdgpu v: kernel pcie:
    gen: 3 speed: 8 GT/s lanes: 16 link-max: gen: 4 speed: 16 GT/s ports:
    active: eDP-1 empty: HDMI-A-1 bus-ID: 03:00.0 chip-ID: 1002:164c
    class-ID: 0300
  Device-2: Quanta USB2.0 HD UVC WebCam type: USB driver: uvcvideo
    bus-ID: 3-3:3 chip-ID: 0408:30d4 class-ID: 0e02 serial: <filter>
  Display: x11 server: X.Org v: 1.21.1.3 compositor: gnome-shell driver: X:
    loaded: amdgpu,ati unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu
    display-ID: :1 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96 s-size: 508x285mm (20.0x11.2")
    s-diag: 582mm (22.9")
  Monitor-1: eDP res: 1920x1080 hz: 60 dpi: 142 size: 344x194mm (13.5x7.6")
    diag: 395mm (15.5")
  OpenGL: renderer: AMD RENOIR (LLVM 13.0.1 DRM 3.42 5.15.0-25-generic)
    v: 4.6 Mesa 22.0.1 direct render: Yes
Audio:
  Device-1: AMD Renoir Radeon High Definition Audio driver: snd_hda_intel
    v: kernel pcie: gen: 3 speed: 8 GT/s lanes: 16 link-max: gen: 4
    speed: 16 GT/s bus-ID: 03:00.1 chip-ID: 1002:1637 class-ID: 0403
  Device-2: AMD Raven/Raven2/FireFlight/Renoir Audio Processor
    vendor: ASUSTeK driver: N/A
    alternate: snd_pci_acp3x, snd_rn_pci_acp3x, snd_pci_acp5x pcie: gen: 3
    speed: 8 GT/s lanes: 16 link-max: gen: 4 speed: 16 GT/s bus-ID: 03:00.5
    chip-ID: 1022:15e2 class-ID: 0480
  Device-3: AMD Family 17h HD Audio vendor: ASUSTeK driver: snd_hda_intel
    v: kernel pcie: gen: 3 speed: 8 GT/s lanes: 16 link-max: gen: 4
    speed: 16 GT/s bus-ID: 03:00.6 chip-ID: 1022:15e3 class-ID: 0403
  Sound Server-1: ALSA v: k5.15.0-25-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel pcie: gen: 2
    speed: 5 GT/s lanes: 1 bus-ID: 01:00.0 chip-ID: 8086:2723 class-ID: 0280
  IF: wlp1s0 state: up mac: <filter>
Bluetooth:
  Device-1: Intel AX200 Bluetooth type: USB driver: btusb v: 0.8
    bus-ID: 3-2:2 chip-ID: 8087:0029 class-ID: e001
  Report: hciconfig ID: hci0 rfk-id: 2 state: up address: <filter>
    bt-v: 3.0 lmp-v: 5.2 sub-v: 237e hci-v: 5.2 rev: 237e
  Info: acl-mtu: 1021:4 sco-mtu: 96:6 link-policy: rswitch sniff
    link-mode: peripheral accept
    service-classes: rendering, capturing, audio, telephony
RAID:
  Device-1: bpool type: zfs status: ONLINE level: linear raw: size: 1.88 GiB
    free: 1012 MiB allocated: 908 MiB zfs-fs: size: 1.75 GiB free: 884.1 MiB
  Components: Online: N/A
  Device-2: rpool type: zfs status: ONLINE level: linear raw: size: 114 GiB
    free: 91 GiB allocated: 23 GiB zfs-fs: size: 110.47 GiB free: 87.07 GiB
  Components: Online: N/A
Drives:
  Local Storage: total: raw: 1.05 TiB usable: 1.16 TiB used: 11.7 GiB (1.0%)
  SMART Message: Required tool smartctl not installed. Check --recommends
  ID-1: /dev/nvme0n1 maj-min: 259:0 vendor: Western Digital
    model: PC SN530 SDBPNPZ-1T00-1002 size: 953.87 GiB block-size:
    physical: 512 B logical: 512 B speed: 31.6 Gb/s lanes: 4 type: SSD
    serial: <filter> rev: 21106000 temp: 33.9 C scheme: GPT
  ID-2: /dev/sda maj-min: 8:0 type: USB vendor: Samsung model: Flash Drive
    size: 119.5 GiB block-size: physical: 512 B logical: 512 B type: SSD
    serial: <filter> rev: 1100 scheme: GPT
Partition:
  ID-1: / raw-size: N/A size: 91.41 GiB used: 4.35 GiB (4.8%) fs: zfs
    logical: rpool/ROOT/ubuntu_ji6uoe
  ID-2: /boot raw-size: N/A size: 1.22 GiB used: 364.6 MiB (29.2%) fs: zfs
    logical: bpool/BOOT/ubuntu_ji6uoe
  ID-3: /boot/efi raw-size: 512 MiB size: 511 MiB (99.80%)
    used: 13.6 MiB (2.7%) fs: vfat dev: /dev/sda1 maj-min: 8:1
  ID-4: /var/log raw-size: N/A size: 87.36 GiB used: 295.5 MiB (0.3%)
    fs: zfs logical: rpool/ROOT/ubuntu_ji6uoe/var/log
Swap:
  Kernel: swappiness: 60 (default) cache-pressure: 100 (default)
  ID-1: swap-1 type: partition size: 2 GiB used: 0 KiB (0.0%) priority: -2
    dev: /dev/dm-1 maj-min: 253:1 mapped: cryptoswap
Sensors:
  System Temperatures: cpu: 42.0 C mobo: N/A gpu: amdgpu temp: 40.0 C
  Fan Speeds (RPM): cpu: 0
Info:
  Processes: 545 Uptime: 1h 4m wakeups: 5 Memory: 15.04 GiB
  used: 5.02 GiB (33.4%) Init: systemd v: 249 runlevel: 5 tool: systemctl
  Compilers: gcc: N/A Packages: 1826 apt: 1813 lib: 900 snap: 13 Shell: Bash
  v: 5.1.16 running-in: gnome-terminal inxi: 3.3.13

**Comment by ajstrongdev** [comment]
Can you try again inside of a virtual machine?

**Comment by PerfMonk** [comment]
I will try, but I don't see why result would be on any way different.  I'll be back soon with confirmation of that.
**update#1**
OK writing this now from rollingrhinoremix 2022.04.19 in a virtual machine under KVM.  I'm not able to log with wayland.  But I could log with Xorg that still work.  I'm on kernel 5.15.0-25.
Next step, I will install latest kernel with rhino-config / rhino-update and try to reboot.
**update#2**
The VM won't boot with kernel 5.17.3.   The zfs module doesn't load or is not present.
![Screenshot_20220124](https://user-images.githubusercontent.com/757849/164603322-7099897e-6813-47c3-8d55-3720cae3bbde.png)

PS: I have a linux nixos running kernel 5.17.3 booting on zfs.  So the zfs module is available for this kernel.

**Comment by ajstrongdev** [comment]
NixOS might make modifications to the Linux kernel. Like Ubuntu does. Can you send me the full kernel version you get after you type "uname-r" on neofetch

**Comment by PerfMonk** [comment]
The rollingrhinoremix version is exactly:  Linux rollingrhino 5.17.3-051703-generic

![Screenshot_20220126](https://user-images.githubusercontent.com/757849/164769439-44f79f18-18ff-465f-9d5c-af806e74676d.png)

NixOs 21.11 on regular channel identify kernel as : 
`[bt@clinix:~]$ uname -a
Linux clinix 5.17.3 #1-NixOS SMP PREEMPT Wed Apr 13 17:27:43 UTC 2022 x86_64 GNU/Linux
`

**Comment by ajstrongdev** [comment]
I see. It seems NixOS has modifications to the Linux kernel which will likely provide ZFS support. Since we use the Ubuntu mainline kernels, they are not necessarily production-ready for Ubuntu use, and should not be used unless you are fully aware of what you are doing. I recommend you use the kernel that is preinstalled with Rolling Rhino Remix for now.

**Comment by PerfMonk** [comment]
It would be better to have a kernel with **all** modules including zfs...  Since the zfs is available for that kernel. 

[https://github.com/openzfs/zfs/releases](url)

I'm very disappointed but understand it is an Ubuntu problem.  But rhino-config should not allow to update to that kernel if you are using zfs since it's not available ...  you should improve that part.

**Comment by ajstrongdev** [comment]
rhino-config is for advanced users, and in the documentation it clearly states that it does not provide support for a lot of modules since it is a Mainline kernel, and not production-ready. It should only be used in circumstances such as if you do not have correct driver support, such as Kernel 5.14 and lower not supporting Intel AX201 wireless chips on Samsung Laptops. 

We currently do not have the capabilities to create a custom kernel and host it, I would love to look into this in the future, however it is not feasible with time constraints and the current size of the development team.
