### ISSUE TITLE
Add support for caching of downloads

### ISSUE THREAD

**Issue by mcassaniti** [rollingrhinoremix/rhino-update#64]
I'm adding support for building Rolling Rhino using mkosi. It would be ideal to cache the downloads that use wget into `/var/cache/apt/archives`. This would allow the cached files to be re-used between any subsequent builds with mkosi. The integration testing as part of the CI process alone would greatly benefit from a change like this.

**Comment by jbrgilbrech** [comment]
Hello! 

I don't see any commits. 
Please link the direct fork on the master repo you are working on with the latest commit changes that are published on rollingrhinoremix/rhino-update:master.

RRR Development.

**Comment by mcassaniti** [comment]
I was somewhat probing to see if it would be accepted or not. Perhaps I should've just dived right in.

**Comment by ajstrongdev** [comment]
> I was somewhat probing to see if it would be accepted or not. Perhaps I should've just dived right in.

In future that is preferred. I prefer to read the code not think about it 🤣
