### ISSUE TITLE
Update Failed 

### ISSUE THREAD

**Issue by Kreblskulm** [rollingrhinoremix/rhino-update#76]
ID                                            Branch         Op
 1. [-] org.freedesktop.Platform.Compat.i386          20.08          r

Uninstall complete.
pacstall-2.0.1.deb  100%[===================>]  17.73K  --.-KB/s    in 0.001s  
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'pacstall' instead of './pacstall-2.0.1.deb'
pacstall is already the newest version (2.0.1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Setting up libdebuginfod-common (0.187-3) ...
Not replacing deleted config file /etc/profile.d/debuginfod.sh
chmod: cannot access '/etc/profile.d/debuginfod.sh': No such file or directory
dpkg: error processing package libdebuginfod-common (--configure):
 installed libdebuginfod-common package post-installation script subprocess retu
rned error exit status 1
No apport report written because the error message indicates it's a follow-up er
ror from a previous failure.
                            dpkg: dependency problems prevent configuration of l
ibdebuginfod1:amd64:
 libdebuginfod1:amd64 depends on libdebuginfod-common (>= 0.187-3); however:
  Package libdebuginfod-common is not configured yet.

dpkg: error processing package libdebuginfod1:amd64 (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 libdebuginfod-common
 libdebuginfod1:amd64
E: Sub-process /usr/bin/dpkg returned an error code (1)

@Henryws

**Comment by ajstrongdev** [comment]
Me and @Henryws will sort it later.

**Comment by Elsie19** [comment]
Install `libdebuginfod-common` and report back the errors.

**Comment by Kreblskulm** [comment]
Cannot install it, i get errors on the install aswell

dpkg: dependency problems prevent configuration of libdebuginfod1:amd64:

**Comment by Elsie19** [comment]
> 2 not fully installed or removed.

This shows that you have a broken apt setup. This is not a Pacstall issue then.
