### ISSUE TITLE
The script is wrong?

### ISSUE THREAD

**Issue by washran** [rollingrhinoremix/rhino-update#78]
wget -q --show-progress --progress=bar:force https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.19.11/amd64/CHECKSUMS &
                                                                                                                                  needs to be v6.0  ^^ 
    wget -q --show-progress --progress=bar:force https://kernel.ubuntu.com/~kernel-ppa/mainline/v6.0/amd64/linux-headers-6.0.0-060000-generic_6.0.0-060000.202210022231_amd64.deb &

**Comment by tricantivu** [comment]
What do you mean @washran?

**Comment by washran** [comment]
See pull request #79. I made necessary corrections, thanks.
